
spring:
  application:
    name: GIS4
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xd3?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#    url: jdbc:mysql://91.229.133.217:58166/xd1?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#    url: jdbc:mysql://192.168.80.129:3306/gis1?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#    username: name
    username : root
    password: 123456
mybatis:
  type-aliases-package: com.ssj.gis4.domain
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
